[package]
name = "tumbler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.18.0"

[profile.release]
overflow-checks = true
lto = true
codegen-units = 1
